# Dockerfile.rooms
FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY room_service /app/room_service

RUN mkdir -p /data

ENV ROOMS_DB_PATH=/data/rooms_secure.db
ENV AUTH_SECRET_KEY=change-me

EXPOSE 5002

WORKDIR /app/room_service
CMD ["python", "app.py"]
