# Dockerfile.bookings
FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY bookings_service /app/bookings_service

RUN mkdir -p /data

ENV BOOKINGS_DB_PATH=/data/bookings_secure.db
ENV AUTH_SECRET_KEY=change-me

EXPOSE 5003

WORKDIR /app/bookings_service
CMD ["python", "app.py"]
